// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWritRc7EYoUvijPPYdr4vESncSpYGxXA',
    appId: '1:177847534638:web:953e4461ce290756f3cbbf',
    messagingSenderId: '177847534638',
    projectId: 'security-survelance',
    authDomain: 'security-survelance.firebaseapp.com',
    storageBucket: 'security-survelance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfoJmojXJYpo3QNjkWddfSYt1T3O__gIE',
    appId: '1:177847534638:android:89c366b278a58f07f3cbbf',
    messagingSenderId: '177847534638',
    projectId: 'security-survelance',
    storageBucket: 'security-survelance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVOQdjzxhS8kOYi7o8UWwl0TmH4a0nz0',
    appId: '1:177847534638:ios:965175e9846989faf3cbbf',
    messagingSenderId: '177847534638',
    projectId: 'security-survelance',
    storageBucket: 'security-survelance.appspot.com',
    iosBundleId: 'com.example.plexis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVOQdjzxhS8kOYi7o8UWwl0TmH4a0nz0',
    appId: '1:177847534638:ios:965175e9846989faf3cbbf',
    messagingSenderId: '177847534638',
    projectId: 'security-survelance',
    storageBucket: 'security-survelance.appspot.com',
    iosBundleId: 'com.example.plexis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWritRc7EYoUvijPPYdr4vESncSpYGxXA',
    appId: '1:177847534638:web:a0afe8daa4ec6a4af3cbbf',
    messagingSenderId: '177847534638',
    projectId: 'security-survelance',
    authDomain: 'security-survelance.firebaseapp.com',
    storageBucket: 'security-survelance.appspot.com',
  );
}
